export const statement = `
INSERT INTO 
  photos (album_id, user_id, url, title )
VALUES
  (?, ?, ?, ?)
`;

export const entries = [
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/118.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_1126.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_1183.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20181219_145820.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20181219_202758.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20181225_160631.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20181227_155331.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20181227_160220.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20181227_163030.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20181229_170035.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20181230_131507.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20181230_133758.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20181230_134104.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20181230_140806.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20181230_142417.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20181230_143819.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20181230_144223.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20181231_130743.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20190101_104046.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20190101_150431.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20190102_155538.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20190102_222222.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20191009_140255-2.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20191012_151728-2.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20191012_164457-2.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_20191016_142516.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_5596.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_5711.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_5986.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_6021.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_6065.jpg",
    "Some Photo",
  ],
  [
    1,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_6081.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_6172.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_6174.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_6202.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_6216.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_6228.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_6268.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_6460.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_6467.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_6483.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_6521.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_6580.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_6593.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_6724.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_6843.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_6850.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_6857.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/IMG_6881.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/Irlande-2022-100.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/Irlande-2022-103.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/Irlande-2022-104.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/Irlande-2022-157.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/Irlande-2022-35.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/Irlande-2022-46.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/Irlande-2022-50.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/Irlande-2022-66.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/Irlande-2022-69.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/Irlande-2022-70.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/Irlande-2022-93.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/Irlande-2022-96.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/Irlande-2022-97.jpg",
    "Some Photo",
  ],
  [
    2,
    1,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/Irlande-2022-99.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/MVIMG_20191010_082628-2.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/MVIMG_20191013_120416-2.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/MVIMG_20191016_144732-2.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/P1050176.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/P1050191.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/P1050211.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/P1050214.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/P1050246.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/P1050272.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/P1050342.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/P1050372.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/P1050377.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/P1050444.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/P1050460-Pano.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/P1100646.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/P1100772.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/P1100806.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/P1100943.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/P1100955.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/P1110198.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/P1110225.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/P1110271.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/PXL_20230305_152031754.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/PXL_20230310_222701023.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/PXL_20230315_000319152.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/PXL_20230316_182846999.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/PXL_20230316_183943116.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/PXL_20230324_191912373.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/PXL_20230410_130039584.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/PXL_20230410_130306873.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/PXL_20230411_173026912.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/PXL_20230417_141031058.jpg",
    "Some Photo",
  ],
  [
    3,
    2,
    "https://francisbourgouin.nyc3.digitaloceanspaces.com/photos/PXL_20230417_141536446.jpg",
    "Some Photo",
  ],
];
